# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT
{{- if .Values.http_route.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "release.fullname" . }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.http_route.gateway.name | default "https" }}
    namespace: {{ .Values.http_route.gateway.namespace | default "envoy-gateway-system" }}
  {{- if .Values.http_route.hostname }}
  hostnames:
  - {{ .Values.http_route.hostname }}
  {{- end }}
  rules:
  - matches:
    {{- if not .Values.http_route.hostname }}
    - headers:
      - name: Host
        type: RegularExpression
        # Matches "appname." followed by any characters
        value: {{ include "release.fullname" . }}\..*
      path:
        type: PathPrefix
        value: /
    {{- else }}
    - path:
        type: PathPrefix
        value: /
    {{- end }}
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "release.fullname" . }}
      port: 80
      weight: 1
    timeouts:
      backendRequest: 3600s
      request: 3605s
{{- end }}
